In [88]:
from plotly.offline import plot
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

from sklearn.preprocessing import MinMaxScaler, StandardScaler
import numpy as np
import pandas as pd
import pickle
# !pip install plotly
import plotly
from sklearn.cluster import KMeans, DBSCAN
from sklearn_extra.cluster import KMedoids

In [90]:
min_max_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

In [68]:
with open('C:/Users/moon/Documents/final_p/after_submit/BASE.bin', 'rb') as f:
    temp = pickle.load(f)
    
temp.columns
df = temp[['GU_CD', 'GU_NM', 'DONG_CD', 'DONG_NM', 'geometry', 'INCOME_RATE', 'AREA_RATE', 'BODY']]

data = df[['INCOME_RATE','AREA_RATE','BODY']]

In [69]:
np.array(data)

array([[ 0.01247097,  0.00449863, -0.20069786],
       [ 0.01043165,  0.03874744, -0.20069786],
       [ 0.02920137,  0.        , -0.20069786],
       ...,
       [ 0.05341681,  0.01523673,  0.30402621],
       [ 0.03603474,  0.84441387,  0.30402621],
       [ 0.06677345,  0.22682496,  0.30402621]])

In [71]:
def k_means(data, clusters, random_state):
    km = KMeans(n_clusters=clusters, init='k-means++', n_init=100, max_iter=300, tol=0.0001, random_state = random_state)
    km.fit(data)
    return np.hstack((data, km.predict(data).reshape(-1,1)))

def k_medoids(data, clusters, random_state):
    km = KMedoids(n_clusters = clusters,
                    init='k-medoids++',
                    max_iter = 300,
                    random_state=random_state)
    km.fit(data)
    return np.hstack((data, km.predict(data).reshape(-1,1)))

In [72]:
def dbscan(data, eps,min_samples,metric='euclidean'):
    db = DBSCAN(eps=eps, min_samples=min_samples)
    pred = db.fit_predict(np.array(data))
    data['cluster'] = db.fit_predict(data)
    return data

In [73]:
def dbscan(data, eps,min_samples,metric='euclidean'):
    db = DBSCAN(eps=eps, min_samples=min_samples)
    pred = db.fit_predict(np.array(data))
    data['cluster'] = db.fit_predict(data)
    return data

def graph_3d(df): #1,2,3열에 데이터, 4열에 클러스터인 배열을 인풋으로 받는다.
    if type(df) == pd.core.frame.DataFrame:
        data = df.values
        data = go.Scatter3d(
            x=data[:,0],
            y=data[:,1],
            z=data[:,2],
            text = ['point #{}'.format(i) for i in range(data.shape[0])],
            mode='markers',
            marker=dict(
                size=3,
                color=data[:,3],
                colorscale='Jet',
                line=dict(
                    #color='rgba(217, 217, 217, 0.14)',
                    #color='rgb(217, 217, 217)',
                    width=0.0
                ),
                opacity=0.8
            )
        )
        layout = go.Layout(
            autosize=False,
            width=750,
            height=750,
            margin=go.Margin(
                l=50,
                r=50,
                b=100,
                t=100,
                pad=4
            ),
            #paper_bgcolor='#7f7f7f',
            #plot_bgcolor='#c7c7c7'
        )
        fig = go.Figure(data=[data], layout=layout)
        iplot(fig)
        
    if type(df) == np.ndarray:
        data = go.Scatter3d(
        x=df[:,0],
        y=df[:,1],
        z=df[:,2],
        text = ['point #{}'.format(i) for i in range(df.shape[0])],
        mode='markers',
        marker=dict(
            size=3,
            color=df[:,3],
            colorscale='Jet',
            line=dict(
                #color='rgba(217, 217, 217, 0.14)',
                #color='rgb(217, 217, 217)',
                width=0.0
            ),
            opacity=0.6
        )
    )

    layout = go.Layout(
        autosize=False,
        width=650,
        height=650,
        margin=go.Margin(
            l=50,
            r=50,
            b=100,
            t=100,
            pad=4
        ),
        #paper_bgcolor='#7f7f7f',
        #plot_bgcolor='#c7c7c7'
    )

    fig = go.Figure(data=[data], layout=layout)
    iplot(fig)


In [74]:
income = min_max_scaler.fit_transform(np.array(data['INCOME_RATE']).reshape(-1,1))

In [76]:
area = min_max_scaler.fit_transform(np.array(data['AREA_RATE']).reshape(-1,1))

In [77]:
body = min_max_scaler.fit_transform(np.array(data['BODY']).reshape(-1,1))

In [78]:
min_max_data = np.hstack((income,area,body))
min_max_data

array([[0.06698844, 0.00449863, 0.45297346],
       [0.05603415, 0.03874744, 0.45297346],
       [0.15685658, 0.        , 0.45297346],
       ...,
       [0.28693103, 0.01523673, 0.63517822],
       [0.19356237, 0.84441387, 0.63517822],
       [0.35867686, 0.22682496, 0.63517822]])

In [91]:
income_standard = standard_scaler.fit_transform(np.array(data['INCOME_RATE']).reshape(-1,1))
area_standard = standard_scaler.fit_transform(np.array(data['AREA_RATE']).reshape(-1,1))
body_standard = standard_scaler.fit_transform(np.array(data['BODY']).reshape(-1,1))
standard_data = np.hstack((income_standard,area_standard,body_standard))

In [112]:
income_standard

array([[-8.16093681e-01],
       [-9.00310886e-01],
       [-1.25182812e-01],
       [-4.14610612e-01],
       [-5.94398806e-01],
       [-1.29698819e+00],
       [-1.18057797e+00],
       [-5.60730801e-01],
       [-1.13109364e+00],
       [-1.27386695e+00],
       [-9.60091907e-01],
       [-7.77258281e-01],
       [ 5.33720768e-01],
       [ 6.35694748e+00],
       [-9.82262788e-01],
       [-1.21167283e+00],
       [-5.87656129e-01],
       [-9.09894775e-01],
       [ 2.36979058e+00],
       [ 1.61903281e+00],
       [-1.21009184e+00],
       [-1.07418873e+00],
       [-1.00742892e-01],
       [-8.89267119e-01],
       [ 1.38445849e+00],
       [-3.19210649e-01],
       [-6.40314958e-01],
       [-7.63407211e-01],
       [-9.43222880e-01],
       [-3.59021752e-01],
       [-8.75407883e-01],
       [-2.80092658e-01],
       [-5.02183160e-01],
       [ 3.51680640e-01],
       [-9.77853096e-01],
       [-1.14762145e+00],
       [ 3.30648616e-01],
       [ 5.72320830e-01],
       [ 3.4

In [115]:
income_standard = standard_scaler.fit_transform(income_standard)

In [107]:
graph_3d(k_means(data,5,4))

C:\Users\moon\anaconda3\envs\single_household\lib\site-packages\plotly\graph_objs\_deprecations.py:410: DeprecationWarning:

plotly.graph_objs.Margin is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.Margin




In [108]:
graph_3d(k_medoids(data,5,4))

C:\Users\moon\anaconda3\envs\single_household\lib\site-packages\plotly\graph_objs\_deprecations.py:410: DeprecationWarning:

plotly.graph_objs.Margin is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.Margin




In [109]:
graph_3d(k_means(min_max_data,5,4))

C:\Users\moon\anaconda3\envs\single_household\lib\site-packages\plotly\graph_objs\_deprecations.py:410: DeprecationWarning:

plotly.graph_objs.Margin is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.Margin




In [110]:
graph_3d(k_medoids(min_max_data,5,4))

C:\Users\moon\anaconda3\envs\single_household\lib\site-packages\plotly\graph_objs\_deprecations.py:410: DeprecationWarning:

plotly.graph_objs.Margin is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.Margin


